# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('tem', models.IntegerField()),
                ('wind', models.CharField(max_length=100)),
                ('cloud', models.CharField(max_length=20)),
                ('schema', models.CharField(max_length=100)),
                ('tips', models.CharField(max_length=200)),
                ('date2', models.DateField()),
                ('tem2', models.IntegerField()),
                ('wind2', models.CharField(max_length=100)),
                ('date3', models.DateField()),
                ('tem3', models.IntegerField()),
                ('wind3', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=500)),
            ],
        ),
    ]
